---

# *** Verify distro.

- set_fact:
    zoidy_distrib_codename_: 'bionic'
  when: ansible_lsb.codename in ['tara', 'tessa', 'tricia',]
  tags: always

- fail: msg="Unexpected distro∷ “{{ ansible_facts.lsb.codename }}”"
  when: zoidy_distrib_codename_ is not defined
  tags: always

# *** Run tasks.

- name: Load role to Download, Get Setup, and Install VirtualBox
  include_role:
    name: zoidy_virtualbox
    tasks_from: app-virtualbox-5
    apply:
      tags:
        - app-virtualbox-5
  vars:
    zoidy_distrib_codename: "{{ zoidy_distrib_codename_ }}"
  tags: app-virtualbox-5

- name: Sign VirtualBox Drivers
  include_role:
    name: zoidy_virtualbox
    tasks_from: app-virtualbox-5-sign
    apply:
      tags:
        - app-virtualbox-5
        - app-virtualbox-5-sign
  tags:
    - app-virtualbox-5
    - app-virtualbox-5-sign

